apiVersion: v1
kind: Secret
metadata:
  name: sovereign-secrets
type: Opaque
stringData:
  jwt-secret: "REPLACE_WITH_32_CHAR_RANDOM"
  hf-token: ""          # optional
  github-token: ""      # optional
