# Sovereign iOS app shell — entry points.
#
# These stubs document the native shell; the actual Swift sources are
# generated by the kivy-ios toolchain (`builds/ios/build_ios.sh`) on macOS.

"""Sovereign iOS shell — AppDelegate equivalent.

This Python module is the entrypoint executed inside the iOS app's
embedded Python runtime. It boots the FastAPI orchestrator so the iOS
app and the BCI/ring hardware talk to the same local sovereign core.
"""

from __future__ import annotations

import asyncio
import threading


def main() -> None:
    import uvicorn

    from sovereign.main import app

    def _serve() -> None:
        uvicorn.run(app, host="127.0.0.1", port=8000, log_level="warning")

    thread = threading.Thread(target=_serve, daemon=True)
    thread.start()
    print("[sovereign] iOS shell booted — orchestrator on 127.0.0.1:8000")


if __name__ == "__main__":
    main()
